In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy.sparse
from sklearn.impute import SimpleImputer

In [3]:
dataset = pd.read_csv('titanic_surv.csv', sep=':')
dataset = pd.read_csv('titanic_surv.csv', sep=None, engine='python')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[[3 'Kelly, Mr. James' 'male' ... 7.8292 nan 'Q']
 [3 'Wilkes, Mrs. James (Ellen Needs)' 'female' ... 7.0 nan 'S']
 [2 'Myles, Mr. Thomas Francis' 'male' ... 9.6875 nan 'Q']
 ...
 [3 'Saether, Mr. Simon Sivertsen' 'male' ... 7.25 nan 'S']
 [3 'Ware, Mr. Frederick' 'male' ... 8.05 nan 'S']
 [3 'Peter, Master. Michael J' 'male' ... 22.3583 nan 'C']]


In [5]:
print(y)

[0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0
 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [6]:
x = pd.DataFrame(x)

In [7]:
x_11 = x.iloc[:, 0:11]

In [8]:
numeric_cols_11 = x_11.select_dtypes(include=[np.number]).columns
non_numeric_cols_11 = x_11.select_dtypes(exclude=[np.number]).columns

In [9]:
if len(numeric_cols_11) > 0:
    # Imputasi missing values untuk kolom numeric menggunakan strategi 'mean'
    imputer_numeric = SimpleImputer(strategy='mean')
    x_11[numeric_cols_11] = imputer_numeric.fit_transform(x_11[numeric_cols_11])

In [10]:
x.iloc[:, 0:11] = x_11

In [11]:
print(x)

     0                                             1       2     3  4  5  \
0    3                              Kelly, Mr. James    male  34.5  0  0   
1    3              Wilkes, Mrs. James (Ellen Needs)  female  47.0  1  0   
2    2                     Myles, Mr. Thomas Francis    male  62.0  0  0   
3    3                              Wirz, Mr. Albert    male  27.0  0  0   
4    3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0  1  1   
..  ..                                           ...     ...   ... .. ..   
413  3                            Spector, Mr. Woolf    male   NaN  0  0   
414  1                  Oliva y Ocana, Dona. Fermina  female  39.0  0  0   
415  3                  Saether, Mr. Simon Sivertsen    male  38.5  0  0   
416  3                           Ware, Mr. Frederick    male   NaN  0  0   
417  3                      Peter, Master. Michael J    male   NaN  1  1   

                      6        7     8  9  
0                330911   7.8292   NaN  Q  

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoser', OneHotEncoder(), [0])])
x = np.array(ct.fit_transform(x))

In [13]:
print(x)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [15]:
print(y)

[0 1 0 0 1 0 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 1
 1 0 0 0 0 0 1 1 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0
 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0
 1 1 1 1 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 1 1 0 0 0 0 0 1 1 0 1 1 0 0 1 0 1
 0 1 0 1 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 0 1 0
 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 0 1
 0 0 0 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0
 0 1 0 0 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 1 0 0 0 0
 0 1 1 1 1 1 0 1 0 0 0]


In [16]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state =1)

In [17]:
print(x_train)

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [18]:
print(x_test)

[[0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0.

In [19]:
print(y_train)

[0 1 1 0 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 1
 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 1 1 1 1 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0
 0 1 1 0 1 0 1 0 0 0 0 0 0 1 1 1 0 1 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 0 1
 0 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 1 1 0 1 1 1 1 0 0 1
 0 0 1 0 1 1 0 1 1 0 0 0 0 1 1 0 0 1 1 0 1 0 0 0 1 0 0 0 0 0 1 1 0 1 1 0 0
 0 0 0 1 1 1 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 0 0 0
 0 0 1 0 1 0 0 1 1 1 0 0 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1
 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 1
 0 0 0 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0
 1]


In [20]:
print(y_test)

[0 0 0 0 1 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0
 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1
 1 1 0 1 0 0 0 0 0 0]


In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 0:11] = sc.fit_transform(x_train[:, 0:11])
x_test[:, 0:11] = sc.transform(x_test[:, 0:11])

In [23]:
print(x_train)

[[-0.61195228 -0.51492865  0.96469469]
 [ 1.63411434 -0.51492865 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 ...
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]]


In [24]:
print(x_test)

[[-0.61195228 -0.51492865  0.96469469]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [ 1.63411434 -0.51492865 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [ 1.63411434 -0.51492865 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [ 1.63411434 -0.51492865 -1.0365974 ]
 [ 1.63411434 -0.51492865 -1.0365974 ]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228  1.94201662 -1.0365974 ]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228 -0.51492865  0.96469469]
 [-0.61195228  1.94201662